Feature/welcome page text+content
VaishaliGovindaraj/JS_Zoo_GroupProject pull request #5
Opened 2024-11-27 16:06 UTC by VaishaliGovindaraj

Hi all,

I have added the welcome page content and added styling for desktop and smaller screen.
Please check and let me know  your comments.

2024-11-27 19:10 UTC, Ankitasingh88 reviewed
Can we add a block in mobile view instead of current view?

2024-11-27 22:46 UTC, Ankitasingh88 approved these changes

2024-11-28 10:21 UTC, Lvhacker1 requested changes

2024-11-28 10:21 UTC, Lvhacker1 commented on scripts/index.js
> +    "Please note that DjurparkExploring a zoo is a fascinating journey into the world of wildlife and conservation. From lush green aviaries to aquatic exhibits, every corner unveils unique habitats
DjurparkExploring?

2024-11-28 10:21 UTC, Lvhacker1 commented on index.html
> +    <nav class="nav_menu">
Why have you made changes here?

2024-11-28 11:23 UTC, PriyeshIllam approved these changes
Looking good to me

2024-11-28 11:28 UTC, VaishaliGovindaraj commented on scripts/index.js
> +    "Please note that DjurparkExploring a zoo is a fascinating journey into the world of wildlife and conservation. From lush green aviaries to aquatic exhibits, every corner unveils unique habitats
there should be a space in between, will add that

2024-11-28 11:29 UTC, VaishaliGovindaraj commented on index.html
> +    <nav class="nav_menu">
for mobile  view layout i needed to remove it since the contents were overflowing

2024-11-28 11:36 UTC, Lvhacker1 commented on scripts/index.js
> +    "Please note that DjurparkExploring a zoo is a fascinating journey into the world of wildlife and conservation. From lush green aviaries to aquatic exhibits, every corner unveils unique habitats
Please make sure to change the name to SafariPark as well.

2024-11-28 11:38 UTC, Lvhacker1 commented on scripts/index.js
> +    "Experience the thrill of getting up close and personal with some of the world’s most fascinating animals through our exclusive Close Encounter programs! At Djurpark, we provide a unique opportun
SafariPark :)

2024-11-28 11:41 UTC, VaishaliGovindaraj commented on scripts/index.js
> +    "Please note that DjurparkExploring a zoo is a fascinating journey into the world of wildlife and conservation. From lush green aviaries to aquatic exhibits, every corner unveils unique habitats
Okay sure

2024-11-28 11:50 UTC, Lvhacker1 commented on scripts/index.js
> +    "SafariPark is open from 9:30-5 pm, all year except Christmas Day.Child entry is for 3-14 year olds. Free entry for children younger than 3 years old.Under 14s need to have an adult with them.Ple
Great job on the update!

2024-11-28 11:50 UTC, Lvhacker1 approved these changes
Great job on the quick change!

2024-11-28 12:01 UTC, Lvhacker1 requested changes

2024-11-28 12:01 UTC, Lvhacker1 commented on scripts/index.js
> +    "SafariPark is open from 9:30-5 pm, all year except Christmas Day.Child entry is for 3-14 year olds. Free entry for children younger than 3 years old.Under 14s need to have an adult with them.Ple
Sorry, you need to update one more thing.

2024-11-28 12:01 UTC, Lvhacker1 commented on scripts/index.js
> +    "SafariPark is open from 9:30-5 pm, all year except Christmas Day.Child entry is for 3-14 year olds. Free entry for children younger than 3 years old.Under 14s need to have an adult with them.Ple
SafariPark is open from 9:30 AM to 5:00 PM, all year except Christmas Day. Child entry is for 3-14 year olds. Free entry for children younger than 3 years old. Children under 14 need to have an adult with them. Please bring your ID, as we offer discounts to students, Community Services card holders, and Gold Card holders. Caregivers of disabled persons are given complimentary entry to the zoo upon presentation of suitable supporting documentation or identification. Please note that SafariPark does not have luggage storage facilities (i.e., lockers). If you have large bags, please chat with one of our Visitor Advisors, who may be able to store them in the front office during your visit.

2024-12-02 13:54 UTC, closed without merging